matrix:
  include:
    - language: swift
      branches:
          only:
              - master
      os: osx
      osx_image: xcode12
      xcode_workspace: Utility Demo.xcworkspace
      xcode_project: Utility Demo.xcodeproj
      xcode_scheme: Utility Demo
      before_install:
          - sudo gem install activesupport -v 4.2.6
          - rvm install 2.3.1
          - rvm use 2.3.1
          - sudo gem install cocoapods
      script:
        - xcodebuild -workspace "Utility Demo.xcworkspace" -scheme "Utility Demo" -sdk iphonesimulator
